[versions]
minestom = "2026.01.08-1.21.11"
adventure = "4.26.1"

# Annotations
jetbrains-annotations = "26.0.2-1"

# Testing
junit-bom = "6.0.0"

# Publishing
maven-publish = "0.34.0"

[libraries]
minestom = { module = "net.minestom:minestom", version.ref = "minestom" }
adventure = { module = "net.kyori:adventure-api", version.ref = "adventure" }

# Annotations
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }

# Testing
minestom-testing = { module = "net.minestom:testing", version.ref = "minestom" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit-bom" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-bom" }

[plugins]
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }